name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Build and Test
        run: make build

      - name: Test package
        run: make go.test

      - name: Test binary
        run: make bin.test
